"""hello

Revision ID: c7c5da7fd9bf
Revises: 
Create Date: 2023-10-13 16:09:07.893140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c5da7fd9bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('p_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_table('children',
    sa.Column('c_name', sa.Text(), nullable=True),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['parents.p_id'], ),
    sa.PrimaryKeyConstraint('c_id')
    )
    op.create_table('sibling',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.Text(), nullable=True),
    sa.Column('c_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_id'], ['children.c_id'], ),
    sa.PrimaryKeyConstraint('s_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sibling')
    op.drop_table('children')
    op.drop_table('parents')
    # ### end Alembic commands ###
